### ISSUE TITLE
Learning

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/Culture#13]
Flush out learning.md with more articles for upcoming staff.

* [x] Web Dev
* [x] DB
* [x] Internals

**Comment by adrianojn** [comment]
Should I edit directly or make a pull request?

**Comment by Zayelion** [comment]
Up to you, idc.

**Comment by adrianojn** [comment]
I've found [this book](https://drive.google.com/file/d/0BydAR5G15GTEZm44WXU3X203V3c/view?usp=sharing) some time ago ([source](http://www.ygopro.co/Forum/tabid/95/g/posts/making-a-guide-for-those-who-want-to-learn-to-make-card-scripts?m=68111#post68111) / [site](http://ygocore.ys168.com/)).
